# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Setup NuGet
        uses: nuget/setup-nuget@v2
        with:
          nuget-version: 'latest'
      - name: Restore dependencies
        run: nuget restore KWHotelDecryptor.sln
      - name: Build
        run: msbuild.exe KWHotelDecryptor.sln /p:Platform="Any CPU" /p:Configuration="Release" /p:TargetFrameworkVersion=v4.7.2
